query BookmarkedQuestions {
    bookmarkedQuestions {
        id
        votes {
            upCount
            downCount
        }
        datastream {
            name
            description
            resultTime
            observedArea
            images
            category
        }
        answers {
            user {
                roles {
                    name
                }
            }
        }
    }
}
