query newestQuestions($size: Int!) {
    newestQuestions (size: $size) {
        id
        votes {
            upCount
            downCount
        }
        datastream {
            name
            description
            resultTime
            observedArea
            images
            category
            properties
        }
        answers {
            user {
                roles {
                    name
                }
            }
        }
    }
}
